@startuml
AsyncTaskManager->SlideshowActivity: filesMissing
AsyncTaskManager->SlideshowActivity: filesFound
AsyncTaskManager->SlideshowActivity: filesAllOk

AsyncTaskManager->SlideshowActivity: imgShown
AsyncTaskManager->SlideshowActivity: noJson

AsyncTaskManager->SlideshowActivity: dlComplete
AsyncTaskManager->SlideshowActivity: dlReceived
AsyncTaskManager->SlideshowActivity: dlStarted



System->SlideshowActivity: startIntent
System->SlideshowActivity: configurationChangedIntent


@enduml
